# This is a basic workflow to help you get started with Actions

name: Build-sphinx-docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    types: [released]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
  # This workflow contains a single job called "build"
  build: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
           python-version: "3.10"
        
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme ghp-import sphinx-autodoc-typehints sphinx-automodapi pydata-sphinx-theme
      # The workflow will create the files shown below and then shortly after, import them into GitHub pages.
      - name: Generate rst files
        run: |
          sphinx-apidoc -o docs/source/ vgslify/
      - name: Build HTML
        run: | 
          cd docs/
          make html
      - name: Run ghp-import
        run: | 
          ghp-import -n -p -f docs/_build/html
