name: Ruff

on:
  pull_request:
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - 'pyproject.toml'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
